-- Made By Alikeremwq#1681
-- Github: https://github.com/Alikeremwq/XAlish
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window  = Library.CreateLib("XAlish Hub","BloodTheme")
local Tab     = Window:NewTab("Basic")
local Section = Tab:NewSection("Basic Cheats")
Section:NewButton("Speed", "Makes You Speedy Boi", function()
   game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 50
   end)
   Section:NewButton("Sonic Speed", "Makes You SONIC!", function()
    game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 150
    end)
Section:NewButton("Fly (J)", "Makes You Fly", function()
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Alikeremwq/XAlish/main/Fly%20(J).lua"))()
end)
Section:NewButton("FullBright", "Makes You See Everything", function()
    loadstring(game:HttpGet(("https://raw.githubusercontent.com/Alikeremwq/XAlish/main/FullBright.lua"),true))()
end)
Section:NewButton("Infinite Jump", "Infinite!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Alikeremwq/XAlish/main/Infinite%20Jump.lua"))()
end)
local Tab = Window:NewTab("Script Hub")
local Section = Tab:NewSection("Scripts For You!")
Section:NewButton("Infinite Yield FE", "Commands And Trolling", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()
end)
Section:NewButton("Legends Of Speed", "Auto Rebirth, Auto Collect Hoops, Auto Farm", function()
    loadstring(game:HttpGet("https://rawscripts.net/raw/Universal-Script-Volatile-10304"))()
end)
Section:NewButton("Pls Donate Hub", "Prettyplease Hub", function()
    loadstring(game:HttpGet('https://tubhub.cloud/scripts/prettyplease.lua', false))()
end)
Section:NewButton("Murder Mystery 2 Hub", "Murder Mystersy Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/vwSaraa/LunarHub/main/mm2"))()
end)
Section:NewButton("Owl Hub", "Universal Aimbot, ESP And More", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/CriShoux/OwlHub/master/OwlHub.txt"))()
end)
Section:NewButton("Car Crushers 2", "Fly, Speed And More", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Alikeremwq/XAlish/main/Car%20Crushers%202.lua"))()
end)
Section:NewButton("Blox Fruits", "Murkuro GUI, Auto Farm", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/xQuartyx/DonateMe/main/ScriptLoader")()
end)
Section:NewButton("Race Clickers", "Race Clicker [Auto Win Race]", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/DEV-TK02/Games/main/RaceClickers', true))()
end)
Section:NewButton("Impossible Glass Bridge Obby", "See Correct Tile, Auto Complete Obby", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/BinaryDex/Scripts/main/IGBO.lua"))()
end)
Section:NewButton("Jenga", "Walkspeed, Instant Win, Remove Killbrick", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Faacts/FactsHub/main/Loader",true))();
end)
Section:NewButton("Universal Speed Coil (Client)", "Speed Coil Client", function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/CJFabro8/Client-Things/main/Speed%20Coil'),true))()
end)
Section:NewButton("Rainbow Friends", "Collect All, ESP", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Ihaveash0rtnamefordiscord/BorkWare/main/Scripts/' .. game.GameId .. ".lua"))(' Watermelon ? ')
end)
Section:NewButton("FE Cockroach (Read Desc)", "https://www.roblox.com/catalog/5674273899/Giant-Isopod-Back-Accessory", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/asbx3rfA"))()
end)
Section:NewButton("Pet Simulator X", "Milk Up Gui", function()
    loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/a82cd5447cbbc4c7be0e8db405555787.lua"))()
end)
Section:NewButton("FE Invisibility", "Universal Invisibility GUI (R15)", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Bebo-Mods/BeboScripts/main/UniversalInvis.lua", true))()
end)
Section:NewButton("Find The Markers GUI", "Unknown Owner", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Alikeremwq/XAlish/main/NOTMYSCRIPT!!!.lua'))()
end)
Section:NewButton("DarkHub", "Arsenal, Aimbot", function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/RandomAdamYT/DarkHub/master/Init'), true))()
end)
Section:NewButton("Doors Entity Spawner", "Plamens Utilities Gui", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/plamen6789/UtilitiesHub/main/UtilitiesGUI'))()
end)
Section:NewButton("Vynixius Doors", "Cool Doors Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RegularVynixu/Vynixius/main/Doors/Script.lua"))()
end)
Section:NewButton("MSDoors", "MSDoors Script (Level 7)", function()
    loadstring(game:HttpGet(("https://raw.githubusercontent.com/mstudio45/MSDOORS/main/MSDOORS.lua"),true))()
end)